version: "3.8"

services:
  model_server:
    build: .
    image: humansignal/the_simplest_backend:v0
    environment:
      - MODEL_DIR=/data/models
      - LABEL_STUDIO_HOST=
      - LABEL_STUDIO_API_KEY=
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"